package export

import (
	"fmt"
	"strings"
	"time"

	"github.com/Luv-Goel/contextflow/internal/db"
)

// ToShellScript exports a workflow as a shell script string.
func ToShellScript(w db.Workflow) string {
	var sb strings.Builder

	name := w.Name
	if name == "" {
		name = fmt.Sprintf("workflow-%d", w.ID)
	}

	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString(fmt.Sprintf("# ContextFlow workflow: %s\n", name))
	if w.GitRepo != "" {
		sb.WriteString(fmt.Sprintf("# Repository: %s\n", w.GitRepo))
	}
	sb.WriteString(fmt.Sprintf("# Recorded: %s\n", w.CreatedAt.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("# Commands: %d\n", len(w.Commands)))
	sb.WriteString("#\n# Generated by ContextFlow — https://github.com/Luv-Goel/contextflow\n\n")
	sb.WriteString("set -euo pipefail\n\n")

	for _, cmd := range w.Commands {
		if cmd.Directory != "" {
			sb.WriteString(fmt.Sprintf("# [%s]\n", shortDir(cmd.Directory)))
		}
		sb.WriteString(cmd.Command + "\n\n")
	}

	return sb.String()
}

// ToMarkdown exports a workflow as a Markdown runbook.
func ToMarkdown(w db.Workflow) string {
	var sb strings.Builder

	name := w.Name
	if name == "" {
		name = fmt.Sprintf("Workflow #%d", w.ID)
	}

	sb.WriteString(fmt.Sprintf("# %s\n\n", name))
	if w.GitRepo != "" {
		sb.WriteString(fmt.Sprintf("**Repository:** `%s`\n\n", w.GitRepo))
	}
	sb.WriteString(fmt.Sprintf("**Recorded:** %s  \n", w.CreatedAt.Format("2006-01-02 15:04")))
	sb.WriteString(fmt.Sprintf("**Commands:** %d\n\n", len(w.Commands)))
	sb.WriteString("---\n\n")
	sb.WriteString("## Steps\n\n")

	for i, cmd := range w.Commands {
		sb.WriteString(fmt.Sprintf("### Step %d\n\n", i+1))
		if cmd.Directory != "" {
			sb.WriteString(fmt.Sprintf("*Directory: `%s`*\n\n", cmd.Directory))
		}
		sb.WriteString(fmt.Sprintf("```bash\n%s\n```\n\n", cmd.Command))
	}

	sb.WriteString("---\n*Generated by [ContextFlow](https://github.com/Luv-Goel/contextflow)*\n")
	return sb.String()
}

func shortDir(dir string) string {
	parts := strings.Split(dir, "/")
	if len(parts) > 2 {
		return "~/" + strings.Join(parts[len(parts)-2:], "/")
	}
	return dir
}
